config/routes.rb
Rails.application.routes.draw do
  root "posts#index"

  resources :posts
  devise_for :users, :controllers => { registrations: 'registrations'}
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user, foreign_key: 'user_id'
    
    validates :body, presence: true, length: {minimum: 1}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy            
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end


  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @post = Post.find(params[:id])
    
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to @post
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to root_path, status: :see_other
  end

  private
    def post_params
      params.require(:post).permit(:body)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    private

    def sign_up_params
        params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end

    def account_update_params
        params.require(:user).permit(:username, :email, :password, :password_confirmation, :current_password)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form_post.html.erb
<%= form_with model: post do |form| %>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
    <% post.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render "form_post", post: @post %>

app/views/posts/index.html.erb
<h1>Members Only</h1><br><br>

<% if user_signed_in? %>
<button><%= link_to "Logout", destroy_user_session_path, data: { "turbo-method": :delete } %></button><br><br>
<% else %>
<button><%= link_to "Sign In", new_user_session_path%></button>

<p>Dont have an account? <button><%= link_to "Sign Up",  new_user_registration_path%></button> and see the authors of our Posts</p><br><br>
<% end %>

<button><%= link_to 'Create new Post', controller: :posts, action: :new %></button><br><br>


<ul>
  <% @posts.each do |post| %>
    <li>
      <% if user_signed_in? %>
      <strong><%= post.user.username %></strong><br>
      <% else%>
      <strong>*****</strong><br>
      <% end %>
      <%= link_to post.body, post, method: :show %>
    </li><br>
  <% end %>
</ul>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render "form_post", post: @post%>

app/views/posts/show.html.erb
<br>
<p><%= @post.body %></p>

<button><%= link_to 'Edit',  edit_post_path, method: :edit%></button>
<button><%= link_to 'Delete',  @post, method: :destroy, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%></button>

<button><%= link_to "Home", posts_path%></button>